"""Database creation

Revision ID: b49ab6037b1f
Revises: 97bf80f63f36
Create Date: 2024-08-31 16:11:46.215301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49ab6037b1f'
down_revision: Union[str, None] = '97bf80f63f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userstobooks_user_id_fkey', 'userstobooks', type_='foreignkey')
    op.create_foreign_key(None, 'userstobooks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userstobooks', type_='foreignkey')
    op.create_foreign_key('userstobooks_user_id_fkey', 'userstobooks', 'roles', ['user_id'], ['id'])
    # ### end Alembic commands ###
